import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import ts from 'typescript';import {z} from 'zod';
const compile=s=>ts.transpileModule(s,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ESNext}}).outputText;
const schemaCode=compile(fs.readFileSync('lib/coffee-schema.ts','utf8').replace(/^import.*\n/,'').replaceAll('export const','const'));
const {coffeeSchema,emptyCoffee}=new Function('z',schemaCode+';return {coffeeSchema,emptyCoffee};')(z);
const route=compile(fs.readFileSync('app/api/analyze-report/route.ts','utf8').replace(/^import.*\n/gm,'').replace('export const runtime','const runtime').replace('export async','async'));
for(const failed of [false,true])test(`análise ${failed?'vazia preserva ficha':'salva automaticamente antes de responder'}`,async()=>{let writes=0;const run=new Function('access','visibleRows','storage','analyzePdf','coffeeProfile','saveCoffeeProfile','coffeeSchema','emptyCoffee',route+';return POST(new Request("https://example.com/api/analyze-report",{method:"POST",body:JSON.stringify({lotId:"lot",documentId:"8f5b008a-12f1-4256-ace7-56698145ae52"})}));');const res=await run(async()=>({role:'admin',owner:'owner'}),async()=>[{id:'8f5b008a-12f1-4256-ace7-56698145ae52',kind:'document',data:{lotId:'lot',key:'private'}}],{get:async()=>new Response('pdf')},async()=>({score:failed?null:86.25,notes:failed?[]:['Coco'],description:failed?'':'Descrição',method:'SCA',reportLot:'1026',warnings:[]}),async()=>({...emptyCoffee,story:'História existente'}),async(id,owner,profile)=>{writes++;assert.equal(profile.score,86.25);assert.equal(profile.story,'História existente');assert.equal(profile.sourceDocumentId,'8f5b008a-12f1-4256-ace7-56698145ae52');},coffeeSchema,emptyCoffee);assert.equal(res.status,failed?422:200);assert.equal(writes,failed?0:1);if(!failed)assert.equal((await res.json()).saved,true);});
const workspace=fs.readFileSync('app/workspace.tsx','utf8');const action=compile(workspace.slice(workspace.indexOf('async function action('),workspace.indexOf('async function deleteLot(')));
for(const failed of [false,true])test(`geração de versão ${failed?'com falha não abre carteira':'encaminha o hash gerado para assinatura'}`,async()=>{let anchors=0;const setters=()=>{};const run=new Function('setError','setFieldErrors','setBusy','fetch','load','setModal','setNotice','setSelected','anchor',action+';return action("version",{lotId:"lot"});');await run(setters,setters,setters,async()=>Response.json(failed?{error:'Falha'}:{id:'version',kind:'version',data:{hash:'hash',snapshot:{stages:[{id:'stage'}]}}},{status:failed?400:200}),async()=>{},setters,setters,setters,async v=>{anchors++;assert.equal(v.id,'version');assert.equal(v.data.hash,'hash');assert.equal(v.data.snapshot.stages[0].id,'stage');});assert.equal(anchors,failed?0:1);});
test('etapas atuais consultam somente lote e proprietário da versão pública',async()=>{const repo=fs.readFileSync('lib/repository.ts','utf8');const code=compile(repo.slice(repo.indexOf('export async function lotStages')).replace('export async','async'));let urls=[];const run=new Function('findRecord','backend','query',code+';return lotStages("lot","owner");');const result=await run(async(id,kind,owner)=>{assert.equal(id,'lot');assert.equal(kind,'lot');assert.equal(owner,'owner');return {data:{}};},async url=>{urls.push(url);return Response.json(urls.length===1?[{id:'stage',data:{type:'Colheita',date:'2026-10-08',description:'Etapa',registeredBy:'producer',secret:'private'}}]:[]);},data=>new URLSearchParams(data).toString());const params=new URLSearchParams(urls[0].split('?')[1]);assert.equal(params.get('owner'),'eq.owner');assert.equal(params.get('kind'),'eq.stage');assert.equal(params.get('data->>lotId'),'eq.lot');assert.deepEqual(result,[{id:'stage',type:'Colheita',date:'2026-10-08',description:'Etapa'}]);});
