"use client";
import {useEffect,useState} from "react";
import {Button} from "@/components/ui/button";
import {Input} from "@/components/ui/input";
const empty={reportLot:"",reportDate:"",variety:"",score:null,method:"SCA",notes:[],description:"",acidity:"",body:"",sweetness:"",finish:"",process:"",altitude:null,story:"",brewing:"",sourceDocumentId:null};
export default function CoffeeProfile({lotId,documents}:{lotId:string;documents:any[]}){
 const [profile,setProfile]=useState<any>(null),[editing,setEditing]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState("");
 useEffect(()=>{const life=new AbortController();setProfile(null);setError("");fetch(`/api/coffee?lotId=${encodeURIComponent(lotId)}`,{signal:life.signal}).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error);setProfile({...empty,...d.profile});}).catch(e=>{if(e.name!=="AbortError")setError(e.message);});return ()=>life.abort();},[lotId]);
 useEffect(()=>{const update=(event:Event)=>{const detail=(event as CustomEvent).detail;if(detail?.lotId!==lotId)return;setProfile({...empty,...detail.profile});setEditing(false);setError("");setNotice("Laudo analisado e ficha salva automaticamente.");};window.addEventListener("coffee-profile-saved",update);return ()=>window.removeEventListener("coffee-profile-saved",update);},[lotId]);
 async function analyze(documentId:string){setBusy(true);setError("");setNotice("");try{const res=await fetch("/api/analyze-report",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({lotId,documentId}),signal:AbortSignal.timeout(30000)});const d=await res.json();if(!res.ok)throw Error(d.error);setProfile({...empty,...d.profile});setEditing(false);setNotice("Laudo analisado e ficha salva automaticamente. Confira os dados; use Editar ficha se precisar corrigir. "+(d.warnings||[]).join(" "));}catch(e:any){setError(e.message||"Não foi possível analisar o laudo.");}finally{setBusy(false);}}
 async function save(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError("");const fields:any=Object.fromEntries(new FormData(e.currentTarget));const data={...fields,score:fields.score===""?null:Number(fields.score.replace(",",".")),altitude:fields.altitude===""?null:Number(fields.altitude),notes:fields.notes.split(",").map((s:string)=>s.trim()).filter(Boolean),sourceDocumentId:fields.sourceDocumentId||null};try{const res=await fetch("/api/coffee",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({lotId,profile:data})});const d=await res.json();if(!res.ok)throw Error(d.error);setProfile(data);setEditing(false);setNotice("Ficha salva. A administradora pode gerar uma nova versão para publicar essas informações.");}catch(e:any){setError(e.message);}finally{setBusy(false);}}
 return <section className="panel mt coffee-editor"><div className="row"><h2>Ficha do café</h2><Button variant="outline" disabled={!profile||busy} onClick={()=>{setEditing(!editing);setNotice("");}}>{editing?"Fechar":"Editar ficha"}</Button></div><div className="row mt">{documents.map(d=><Button key={d.id} variant="outline" disabled={busy||!profile} onClick={()=>analyze(d.id)}>{busy?"Analisando…":"Reanalisar laudo"} · {d.data.name}</Button>)}</div><p className="muted">Preencha a nota conforme o laudo. Salvar a ficha não altera versões já registradas.</p>{error&&<p role="alert" className="form-error">{error}</p>}{notice&&<p role="status" className="alert">{notice}</p>}{!profile&&!error?<p>Carregando ficha…</p>:editing&&profile?<form key={JSON.stringify(profile)} className="form" onSubmit={save}><div className="coffee-fields"><label>Nota final (0 a 100)<Input name="score" inputMode="decimal" defaultValue={profile.score??""} placeholder="Ex.: 86,25"/></label><label>Metodologia<Input name="method" maxLength={80} defaultValue={profile.method}/></label><label>Laudo da pontuação<select name="sourceDocumentId" defaultValue={profile.sourceDocumentId||""}><option value="">Sem laudo selecionado</option>{documents.map(d=><option key={d.id} value={d.id}>{d.data.name}</option>)}</select></label><label>Lote informado no laudo<Input name="reportLot" maxLength={80} defaultValue={profile.reportLot}/></label><label>Data do laudo<Input name="reportDate" type="date" defaultValue={profile.reportDate}/></label><label>Variedade<Input name="variety" maxLength={80} defaultValue={profile.variety}/></label><label>Altitude em metros<Input name="altitude" type="number" min="0" max="9000" defaultValue={profile.altitude??""}/></label></div><label>Notas sensoriais, separadas por vírgula<Input name="notes" defaultValue={profile.notes.join(", ")} placeholder="Abacaxi, coco, baunilha"/></label>{[["process","Processamento"],["acidity","Acidez"],["body","Corpo"],["sweetness","Doçura"],["finish","Finalização"]].map(([key,label])=><label key={key}>{label}<Input name={key} maxLength={2000} defaultValue={profile[key]}/></label>)}{[["description","Descrição sensorial do laudo"],["story","História deste café (opcional)"],["brewing","Sugestão de preparo (opcional)"]].map(([key,label])=><label key={key}>{label}<textarea name={key} maxLength={2000} rows={3} defaultValue={profile[key]}/></label>)}<Button disabled={busy}>{busy?"Salvando…":"Salvar ficha do café"}</Button></form>:profile?<><div className="coffee-summary"><strong>{profile.score!==null?`${Number(profile.score).toLocaleString("pt-BR")} pontos ${profile.method}`:"Pontuação não informada"}</strong><p>{profile.notes.length?profile.notes.join(" · "):"Notas sensoriais ainda não informadas."}</p><p className="muted">{profile.description}</p>{profile.reportLot&&<p className="muted">Lote no laudo: {profile.reportLot}. Confira se o documento corresponde ao café deste cadastro antes de gerar a versão.</p>}</div></>:null}</section>;
}
