import {insertRecord,coffeeProfile,publications,removeLot} from "@/lib/repository";

import {access,visibleRows,readRows} from "@/lib/access";
import {producerMayWrite,producerPublications} from "@/lib/access-policy";
import { digest } from "@/lib/trace";
import { z } from "zod";
const schemas:any={producer:z.object({name:z.string().trim().min(2).max(120)}),property:z.object({name:z.string().trim().min(2).max(120),producerId:z.string().uuid(),city:z.string().trim().min(2).max(100),state:z.string().length(2)}),lot:z.object({code:z.string().trim().min(2).max(60),propertyId:z.string().uuid(),species:z.string().trim().min(1).max(80),variety:z.string().trim().max(80).default(""),harvest:z.string().min(4).max(20),quantity:z.preprocess(v=>typeof v==="string"?Number(v.trim().replace(",",".")):v,z.number().finite().positive().max(1e9))}),stage:z.object({lotId:z.string().uuid(),type:z.string().min(1).max(80),date:z.string().regex(/^\d{4}-\d{2}-\d{2}$/),description:z.string().trim().max(2000).default("")})};
export async function GET(){try{const a=await access();if(!a||a.role==="denied")return Response.json({error:"Acesso não autorizado."},{status:403});const rows=await visibleRows(a);if(a.role==="admin"){const published=await publications(a.owner);return Response.json(rows.map(r=>({...r,publishedAt:published.find((p:any)=>p.version_id===r.id)?.published_at||null})));}const published=await publications(a.owner!);const all=await readRows(a.owner);const versions=all.map(r=>({...r,publishedAt:published.find((p:any)=>p.version_id===r.id)?.published_at||null}));return Response.json([...rows,...producerPublications(versions,a.producerId!)]);}catch{return Response.json({error:"Não foi possível carregar os cadastros."},{status:503});}}
export async function POST(req:Request){try{const a=await access();if(!a||a.role==="denied")return Response.json({error:"Acesso não autorizado."},{status:403});const b=await req.json() as any;if(!b||typeof b.kind!=="string"||!b.data||typeof b.data!=="object")return Response.json({error:"Dados do formulário inválidos. Reabra o cadastro."},{status:400});const id=crypto.randomUUID();let data:any;
const all=await visibleRows(a);if(a.role==="producer"&&!producerMayWrite(b.kind,b.data,all))return Response.json({error:"Você pode criar lotes e registrar etapas somente da sua propriedade."},{status:403});const find=(id:string,kind:string)=>all.find((r:any)=>r.id===id&&r.kind===kind);
if(b.kind==="version"){const lot=find(b.data.lotId,"lot");if(!lot)return Response.json({error:"Lote não encontrado."},{status:404});const property=find(lot.data.propertyId,"property"),producer=find(property?.data.producerId,"producer");if(!property||!producer)throw Error("Origem incompleta.");const stages=all.filter((r:any)=>r.kind==="stage"&&r.data.lotId===lot.id).map((r:any)=>({id:r.id,...r.data})).sort((a:any,b:any)=>a.date.localeCompare(b.date)||a.id.localeCompare(b.id));const number=all.filter((r:any)=>r.kind==="version"&&r.data.lotId===lot.id).length+1;const documents=all.filter((r:any)=>r.kind==="document"&&r.data.lotId===lot.id).map((r:any)=>({id:r.id,name:r.data.name,size:r.data.size,hash:r.data.hash})).sort((a:any,b:any)=>a.id.localeCompare(b.id));const coffee=await coffeeProfile(lot.id,a.owner!);const snapshot={coffee,formatVersion:3,version:number,lot:{id:lot.id,...lot.data},property:{id:property.id,...property.data},producer:{id:producer.id,...producer.data},stages,documents};data={lotId:lot.id,number,snapshot,hash:await digest(snapshot),signature:null,wallet:null};}
else{if(!schemas[b.kind])return Response.json({error:"Tipo inválido."},{status:400});data=schemas[b.kind].parse(b.data);if(b.kind==="property"&&!find(data.producerId,"producer"))throw Error("Produtor inválido.");if(b.kind==="lot"&&!find(data.propertyId,"property"))throw Error("Propriedade inválida.");if(b.kind==="lot"&&all.some((r:any)=>r.kind==="lot"&&r.data.code.toLowerCase()===data.code.toLowerCase()))throw Error("Já existe um lote com esse código.");if(b.kind==="stage"&&!find(data.lotId,"lot"))throw Error("Lote inválido.");if(b.kind==="stage"){const parsed=new Date(data.date+"T12:00:00Z");if(Number.isNaN(parsed.getTime())||parsed.toISOString().slice(0,10)!==data.date)throw Error("Data inválida.");const today=new Intl.DateTimeFormat("en-CA",{timeZone:"America/Manaus"}).format(new Date());if(data.date>today)throw Error("A etapa não pode ter uma data futura.");if(all.some((r:any)=>r.kind==="stage"&&r.data.lotId===data.lotId&&r.data.type===data.type&&r.data.date===data.date))throw Error("Esta etapa já foi registrada para este lote nesta data.");data.registeredBy=a.role==="producer"?"producer":"admin";}}
await insertRecord({id,owner:a.owner,kind:b.kind,data,created:new Date().toISOString()});return Response.json({id,data,kind:b.kind});}catch(e:any){return Response.json({error:e instanceof z.ZodError?"Confira os campos indicados abaixo.":e instanceof SyntaxError?"Não foi possível ler o formulário. Tente novamente.":e.message||"Não foi possível salvar." ,fieldErrors:e instanceof z.ZodError?Object.fromEntries(e.issues.map(i=>[i.path[0],({name:"Informe um nome com 2 a 120 caracteres.",code:"Informe um código com 2 a 60 caracteres.",propertyId:"Selecione uma propriedade cadastrada.",producerId:"Selecione um produtor cadastrado.",species:"Informe a espécie do café (até 80 caracteres).",variety:"Use até 80 caracteres para a variedade.",harvest:"Informe a safra com 4 a 20 caracteres, por exemplo 2026.",quantity:"Informe uma quantidade maior que zero, em kg (até 1 bilhão).",city:"Informe o município com 2 a 100 caracteres.",state:"Informe a UF com duas letras.",date:"Informe uma data válida.",description:"Use até 2000 caracteres na descrição."} as Record<string,string>)[String(i.path[0])]||"Confira este campo."])):undefined},{status:400});}}

export async function DELETE(req:Request){
 try{
 const a=await access();if(!a||a.role!=="admin")return Response.json({error:"Somente administradores podem excluir lotes."},{status:403});
 const input=await req.json();const parsed=z.object({id:z.string().uuid()}).safeParse(input);
 if(!parsed.success)return Response.json({error:"Identificação do lote inválida."},{status:400});
 const rows=await visibleRows(a),lot=rows.find(r=>r.kind==="lot"&&r.id===parsed.data.id);
 if(!lot)return Response.json({error:"Lote não encontrado."},{status:404});
 await removeLot(lot.id,a.owner!,{...lot.data,deletedAt:new Date().toISOString(),deletedBy:a.user.userId});
 return Response.json({ok:true});
 }catch{return Response.json({error:"Não foi possível excluir o lote. Tente novamente."},{status:503});}
}
